#define FASTKPC_MULTI_PENALTY_MAX_COEFFICIENT_DIM 559
#define FASTKPC_MULTI_PENALTY_MAX_PENALTY_COUNT 62
#define lapack312_multi lapack312_multi_ext559
#define MultiPenaltyGcvCudaPrepared MultiPenaltyGcvCudaPreparedext559
#define MultiPenaltyGcvCudaResidualBatch MultiPenaltyGcvCudaResidualBatchext559
#define MultiPenaltyGcvCudaBatchResult MultiPenaltyGcvCudaBatchResultext559
#define MultiPenaltyGcvCudaMultiRequest MultiPenaltyGcvCudaMultiRequestext559
#define MultiPenaltyGcvCudaMultiResult MultiPenaltyGcvCudaMultiResultext559
#define multi_penalty_gcv_evaluate_cuda multi_penalty_gcv_evaluate_cuda_ext559
#define multi_penalty_gcv_grouped_evaluate_prototype_cuda \
  multi_penalty_gcv_grouped_evaluate_prototype_cuda_ext559
#define multi_penalty_gcv_optimize_cuda multi_penalty_gcv_optimize_cuda_ext559
#define create_multi_penalty_gcv_cuda_prepared \
  create_multi_penalty_gcv_cuda_prepared_ext559
#define multi_penalty_gcv_cuda_prepared_info \
  multi_penalty_gcv_cuda_prepared_info_ext559
#define multi_penalty_gcv_cuda_optimize_batch \
  multi_penalty_gcv_cuda_optimize_batch_ext559
#define multi_penalty_gcv_cuda_optimize_multi \
  multi_penalty_gcv_cuda_optimize_multi_ext559
#define multi_penalty_gcv_cuda_residual_info \
  multi_penalty_gcv_cuda_residual_info_ext559
#define acquire_multi_penalty_gcv_cuda_residual_consumer_view \
  acquire_multi_penalty_gcv_cuda_residual_consumer_view_ext559
#define materialize_multi_penalty_gcv_cuda_residual_shadow \
  materialize_multi_penalty_gcv_cuda_residual_shadow_ext559
#define release_multi_penalty_gcv_cuda_residual \
  release_multi_penalty_gcv_cuda_residual_ext559

#include "mgcv_multi_penalty_gcv.cu"
