#define FASTKPC_MULTI_PENALTY_MAX_COEFFICIENT_DIM 64
#define FASTKPC_MULTI_PENALTY_MAX_PENALTY_COUNT 7
#define lapack312_multi lapack312_multi_small64
#define MultiPenaltyGcvCudaPrepared MultiPenaltyGcvCudaPreparedsmall64
#define MultiPenaltyGcvCudaResidualBatch MultiPenaltyGcvCudaResidualBatchsmall64
#define MultiPenaltyGcvCudaBatchResult MultiPenaltyGcvCudaBatchResultsmall64
#define MultiPenaltyGcvCudaMultiRequest MultiPenaltyGcvCudaMultiRequestsmall64
#define MultiPenaltyGcvCudaMultiResult MultiPenaltyGcvCudaMultiResultsmall64
#define multi_penalty_gcv_evaluate_cuda multi_penalty_gcv_evaluate_cuda_small64
#define multi_penalty_gcv_grouped_evaluate_prototype_cuda \
  multi_penalty_gcv_grouped_evaluate_prototype_cuda_small64
#define multi_penalty_gcv_optimize_cuda multi_penalty_gcv_optimize_cuda_small64
#define create_multi_penalty_gcv_cuda_prepared \
  create_multi_penalty_gcv_cuda_prepared_small64
#define multi_penalty_gcv_cuda_prepared_info \
  multi_penalty_gcv_cuda_prepared_info_small64
#define multi_penalty_gcv_cuda_optimize_batch \
  multi_penalty_gcv_cuda_optimize_batch_small64
#define multi_penalty_gcv_cuda_optimize_multi \
  multi_penalty_gcv_cuda_optimize_multi_small64
#define multi_penalty_gcv_cuda_residual_info \
  multi_penalty_gcv_cuda_residual_info_small64
#define acquire_multi_penalty_gcv_cuda_residual_consumer_view \
  acquire_multi_penalty_gcv_cuda_residual_consumer_view_small64
#define materialize_multi_penalty_gcv_cuda_residual_shadow \
  materialize_multi_penalty_gcv_cuda_residual_shadow_small64
#define release_multi_penalty_gcv_cuda_residual \
  release_multi_penalty_gcv_cuda_residual_small64

#include "mgcv_multi_penalty_gcv.cu"
