#define FASTKPC_MULTI_PENALTY_MAX_COEFFICIENT_DIM 192
#define FASTKPC_MULTI_PENALTY_MAX_PENALTY_COUNT 21
#define lapack312_multi lapack312_multi_ext192
#define MultiPenaltyGcvCudaPrepared MultiPenaltyGcvCudaPreparedext192
#define MultiPenaltyGcvCudaResidualBatch MultiPenaltyGcvCudaResidualBatchext192
#define MultiPenaltyGcvCudaBatchResult MultiPenaltyGcvCudaBatchResultext192
#define MultiPenaltyGcvCudaMultiRequest MultiPenaltyGcvCudaMultiRequestext192
#define MultiPenaltyGcvCudaMultiResult MultiPenaltyGcvCudaMultiResultext192
#define multi_penalty_gcv_evaluate_cuda multi_penalty_gcv_evaluate_cuda_ext192
#define multi_penalty_gcv_grouped_evaluate_prototype_cuda \
  multi_penalty_gcv_grouped_evaluate_prototype_cuda_ext192
#define multi_penalty_gcv_optimize_cuda multi_penalty_gcv_optimize_cuda_ext192
#define create_multi_penalty_gcv_cuda_prepared \
  create_multi_penalty_gcv_cuda_prepared_ext192
#define multi_penalty_gcv_cuda_prepared_info \
  multi_penalty_gcv_cuda_prepared_info_ext192
#define multi_penalty_gcv_cuda_optimize_batch \
  multi_penalty_gcv_cuda_optimize_batch_ext192
#define multi_penalty_gcv_cuda_optimize_multi \
  multi_penalty_gcv_cuda_optimize_multi_ext192
#define multi_penalty_gcv_cuda_residual_info \
  multi_penalty_gcv_cuda_residual_info_ext192
#define acquire_multi_penalty_gcv_cuda_residual_consumer_view \
  acquire_multi_penalty_gcv_cuda_residual_consumer_view_ext192
#define materialize_multi_penalty_gcv_cuda_residual_shadow \
  materialize_multi_penalty_gcv_cuda_residual_shadow_ext192
#define release_multi_penalty_gcv_cuda_residual \
  release_multi_penalty_gcv_cuda_residual_ext192

#include "mgcv_multi_penalty_gcv.cu"
