#define FASTKPC_MULTI_PENALTY_MAX_COEFFICIENT_DIM 384
#define FASTKPC_MULTI_PENALTY_MAX_PENALTY_COUNT 42
#define lapack312_multi lapack312_multi_ext384
#define MultiPenaltyGcvCudaPrepared MultiPenaltyGcvCudaPreparedext384
#define MultiPenaltyGcvCudaResidualBatch MultiPenaltyGcvCudaResidualBatchext384
#define MultiPenaltyGcvCudaBatchResult MultiPenaltyGcvCudaBatchResultext384
#define MultiPenaltyGcvCudaMultiRequest MultiPenaltyGcvCudaMultiRequestext384
#define MultiPenaltyGcvCudaMultiResult MultiPenaltyGcvCudaMultiResultext384
#define multi_penalty_gcv_evaluate_cuda multi_penalty_gcv_evaluate_cuda_ext384
#define multi_penalty_gcv_grouped_evaluate_prototype_cuda \
  multi_penalty_gcv_grouped_evaluate_prototype_cuda_ext384
#define multi_penalty_gcv_optimize_cuda multi_penalty_gcv_optimize_cuda_ext384
#define create_multi_penalty_gcv_cuda_prepared \
  create_multi_penalty_gcv_cuda_prepared_ext384
#define multi_penalty_gcv_cuda_prepared_info \
  multi_penalty_gcv_cuda_prepared_info_ext384
#define multi_penalty_gcv_cuda_optimize_batch \
  multi_penalty_gcv_cuda_optimize_batch_ext384
#define multi_penalty_gcv_cuda_optimize_multi \
  multi_penalty_gcv_cuda_optimize_multi_ext384
#define multi_penalty_gcv_cuda_residual_info \
  multi_penalty_gcv_cuda_residual_info_ext384
#define acquire_multi_penalty_gcv_cuda_residual_consumer_view \
  acquire_multi_penalty_gcv_cuda_residual_consumer_view_ext384
#define materialize_multi_penalty_gcv_cuda_residual_shadow \
  materialize_multi_penalty_gcv_cuda_residual_shadow_ext384
#define release_multi_penalty_gcv_cuda_residual \
  release_multi_penalty_gcv_cuda_residual_ext384

#include "mgcv_multi_penalty_gcv.cu"
